theme: jekyll-theme-cayman
title: Practical Open-Loop Optimistic Planning
description: Edouard Leurent, Odalric-Ambrym Maillard

github:
  repository_url: https://github.com/eleurent/rl-agents#olop-open-loop-optimistic-planning
  paper_url: https://arxiv.org/abs/1904.04727